apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels: 
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: 773867802764.dkr.ecr.us-west-2.amazonaws.com/home-project:home-project-build-latest
        imagePullPolicy: Always
        ports:
        - name: hello
          containerPort: 5000
          protocol: TCP
